### ISSUE TITLE
Empty cells in collapsed sensor data per seq csv file

### ISSUE THREAD

**Issue by Ting-Kerbell** [tufts-ml/time_series_prediction#12]
When I collapse my activities sensor data, the resulting csv file has mostly empty cells for the non-ID columns. The data is in random chunks throughout the csv (EX. there is information for subject_id=1, seq_id=1 through 5 and 153 - 162, but nothing in between). Is there something wrong with how I ran the scripts in the make file, or am I missing the reasoning behind this?
 
![why1](https://user-images.githubusercontent.com/13530966/66540870-45306080-eafb-11e9-99e9-475c0541c9e2.PNG)
![why2](https://user-images.githubusercontent.com/13530966/66540871-45306080-eafb-11e9-999d-693cb82c4e29.PNG)

**Comment by michaelchughes** [comment]
Thanks @Ting-Kerbell

Please fix and send a PR! Find how to make sure collapsing only delivers (subj_id, seq_id) pairs that were present in the input data it was fed. Seems like that's the issue here (there's some assumption in the code that each subj has seq_ids 1, 2,3 ..... MAX

**Comment by michaelchughes** [comment]
@Ting-Kerbell did this get resolved? If so, please mark as resolved...

**Comment by Ting-Kerbell** [comment]
I resolved the issue, but will make the pull request either tonight or
tomorrow.
