### ISSUE TITLE
Logistic Regression Classifier has subject_id and episode_id as features

### ISSUE THREAD

**Issue by rathp** [tufts-ml/time_series_prediction#13]
While fitting the logistic regression classifier to the data in src/logistic/main_mimic.py, the classifier.fit() method is applied to the data frame containing subject_id and episode_id as features as well. 

existing code : 
best_logistic = classifier.fit(X_train, y_train)

fix : 
best_logistic = classifier.fit(X_train.iloc[:,2:], y_train) # exclude first 2 columns(subject_id, episode_id) from features.

**Comment by michaelchughes** [comment]
@rathp did this get resolved? If so, please mark as resolved. If not, please add a fix via PR

**Comment by rathp** [comment]
This issue is resolved in the logistic regression pipeline.
