### ISSUE TITLE
Importing Torch with the tspred_env python environment throws an error

### ISSUE THREAD

**Issue by rathp** [tufts-ml/time_series_prediction#16]
Importing torch with the our time series predict python environment 'tspred_env', throws the following error:
```
  File "SkorchLogisticRegressionModule.py", line 2, in <module>
    import torch
  File "/cluster/tufts/hugheslab/miniconda2/lib/python3.7/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cluster/tufts/hugheslab/miniconda2/lib/python3.7/site-packages/torch/_C.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by michaelchughes** [comment]
Not an issue with this repo. This is an issue with the default glibc
library available on the cluster

See this note

https://gist.github.com/michaelchughes/85287f1c6f6440c060c3d86b4e7d764b

**Comment by michaelchughes** [comment]
I can get it fixed. Give me the yml file for the env you want and I'll
install it later tonight

**Comment by michaelchughes** [comment]
Or you are welcome to install yourself if you wanna try that readme of
instructions

**Comment by rathp** [comment]
This isn't a pressing issue. I'm using the bdl2019f_readonly env file for now. I noted this as an issue as it wasn't noted here.

**Comment by michaelchughes** [comment]
Resolved as a non-issue with this repo.
