### ISSUE TITLE
Normalizing features passes information from test to train data

### ISSUE THREAD

**Issue by rathp** [tufts-ml/time_series_prediction#18]
Script normalize_features.py uses scikit learn's robust_scaler to normalize our entire dataset, which could pass information from our test to our training data. 

Solution : perform any normalization as a part of the classifier's pipeline.

**Comment by michaelchughes** [comment]
Is this resolved? If so can you mark it as such and close it?

**Comment by rathp** [comment]
Resolved. Closing!
