### ISSUE TITLE
Create standardized data makefile

### ISSUE THREAD

**Issue by byronperpetua** [tufts-ml/time_series_prediction#2]
* [x] make dataset_split_into_train_valid_test @byronperpetua 
* [x] make dataset_interpolate_to_regular_tsteps @byronperpetua 
* [x] make dataset_fill_missing_values @onewland13 
* [x] data dictionary @byronperpetua 
* [x] feature standardization @byronperpetua 
* [x] feature transformation @onewland13 
* [x] think about static data @byronperpetua (can test with eeg data, where outcomes happen to be static)
* [x] put it all together into a makefile @byronperpetua 
* [x] deploy pipeline on EEG data (use build_std_eeg_data_from_raw.py)

Makefile order: align to grid, fill missing, standardize features, transform features, split

Data dictionary: see https://github.com/dtak/mimic_icu_datapackage

Feature standardization: robust to outliers, determines which feature should be standardized (e.g. not booleans) from data dictionary

Feature transformation: Optional step with two possible functionalities:
- Collapse time dimension and calculate summary statistics, as with EEG data
- Create new features (e.g. square of existing feature)
- When creating new features, create a new copy of the data dictionary with the new columns added (or a similar solution)

Missing values: 
- fill with population mean
- carry forward
- (maybe) fill with mean for similar subjects
- (maybe) GRU simple
- (maybe) new variables indicating missing and time since last measurement

**Comment by michaelchughes** [comment]
Closing. This was solid progress, and we have a Snakemake workflow for this now.
