### ISSUE TITLE
Create classifier infrastructure

### ISSUE THREAD

**Issue by byronperpetua** [tufts-ml/time_series_prediction#5]
Write code that accepts generic standardized data and runs and evaluates some classifier to be specified.

- For now, focus on binary classifiers. May include regression in the future.
- For now, assume each row is independent. For MIMIC, will want to make predictions based on past data.
- Combine time-series data with static data
- Use the data dictionary to identify what role each column plays (ID, outcome, input data, time/sequence)

[Example](https://github.com/dtak/prediction-constrained-topic-models/blob/master/pc_toolbox/binary_classifiers/train_and_eval_sklearn_binary_classifier.py).

**Comment by michaelchughes** [comment]
Added. Thanks.
