### ISSUE TITLE
Fix feature_transformation.py pandas.pivot_table drops columns of all NaNs incorrectly

### ISSUE THREAD

**Issue by onewland13** [tufts-ml/time_series_prediction#9]
Putting this here so we remember to fix later. 

pivot_table currently has a bug where setting its dropna parameter to False is not respected. Empty columns are dropped where they should be simply filled with NaNs. This is a known bug and they are working on fixing it, should be out in the next version on pandas (0.25, we are currently on 0.24.2): https://github.com/pandas-dev/pandas/pull/25738

**Comment by michaelchughes** [comment]
Tagging both Preetish (@rathp, new PhD student excited to invent new time-series models for clinical applications) and Byron (@byronperpetua, one of the awesome MS students who helped make this repo what it is today)

I've talked to you both recently about how feature_transformation.py has a few big problems:
1) It is slow (Preetish reports ~1 hour or more to compute the features for data with ~1 million rows and ~20k distinct subjects)
2) It is bad at dealing with NaNs (unclear what it does if fed all NaNs, or if no data exists, etc)

@byronperpetua has volunteered to take lead on fixing these issues. I hope you can both coordinate to get that done (ping here with any questions, etc). 

## Prelim Evidence that we should be much faster than a few hours

You should be able to compute the per-subject mean for a dataset on MIMIC scale (20000 subjects, about 1 million rows total) in <1 sec (and not much longer for slope or other features)
See code here: https://gist.github.com/michaelchughes/e550d509624eae1305de7cdeb3dd8382

When I run on my laptop, here's expected output:

Computed the per-subj mean of 20000 subjects and 1000000 rows in 0.15 sec
-0.33963816696930393
-0.33963816696930393
Check for subj 0 PASSED
-0.17222106262010406
-0.17222106262010406
Check for subj 333 PASSED
-0.11133756578591823
-0.11133756578591823
Check for subj 2345 PASSED
0.014000856116237057
0.014000856116237057
Check for subj 16789 PASSED
0.19369435622090317
0.19369435622090317
Check for subj 19999 PASSED

**Comment by michaelchughes** [comment]
This has been integrated. Thanks all.
